### ISSUE TITLE
Step failure in upgrading ASP.Net Library

### ISSUE THREAD

**Issue by kakiser56** [dotnet/modernize-dotnet#1398]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Below is the stop. operation, and stack trace.

[09:32:18 INF] Applying upgrade step Apply fix for UA0005: Do not use HttpContext.Current
[09:32:18 ERR] Unexpected error applying step
System.ArgumentException: 'namespaceName' cannot be null or empty. (Parameter 'namespaceName')
   at Microsoft.DotNet.UpgradeAssistant.Extensions.Default.SyntaxNodeExtensions.AddImportIfMissing(CompilationUnitSyntax documentRoot, String namespaceName) in /_/src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.Common/SyntaxNodeExtensions.cs:line 206
   at Microsoft.DotNet.UpgradeAssistant.Extensions.Default.CodeFixes.HttpContextCurrentCodeFixer.ReplaceHttpContextCurrentAsync(Document document, SyntaxNode node, CancellationToken cancellationToken) in /_/src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.CodeFixes/HttpContextCurrentCodeFixer.cs:line 99
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(IProgressTracker progressTracker, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(IProgressTracker progressTracker, CancellationToken cancellationToken)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.TryFixDiagnosticAsync(Diagnostic diagnostic, Document document, CancellationToken token) in /_/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Source/CodeFixerStep.cs:line 196
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.ApplyImplAsync(IUpgradeContext context, CancellationToken token) in /_/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Source/CodeFixerStep.cs:line 105
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 178
Command (Apply next step (Apply fix for UA0005: Do not use HttpContext.Current)) did not succeed

**Comment by lunchin** [comment]
Looks like it s failing because there no namespace for the file in question.
