### ISSUE TITLE
Analysing / Updating to SDK a Framework 4.8 vb.net dll project file.

### ISSUE THREAD

**Issue by RocktimeLtd** [dotnet/modernize-dotnet#1615]
Analysing / Updating to SDK a Framework 4.8 vb.net dll project file.

Steps to reproduce.

Create a brand new Framework 4.8 vb Class library.
Try to analyse it using command line tool in powershell. Trying to upgrade to sdk via vs extension hangs at Starting upgrade of selected nodes for TestUpgrade.vbproj...

Error

Selected options
─────────────────────────────────────────────────────────────────────────────────────────────────
 Analysis settings   code
 Privacy mode        Unrestricted
 Report format       Html
 Report name         b
 Selected projects   C:\LocalDev\RocktimeLogic\NET\10-FixingRefs\TestUpgrade\TestUpgrade.vbproj
 Source              Solution
 Target framework    .NET 6.0 (Supported until November, 2024)

 Steps
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Source / Target framework / Projects / Settings / Config file / Report format / Report name / Privacy / Analysis
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

We have gathered all required options and are ready to run analysis. Do you want to continue? [y/n] (y): y
Building project 'C:\LocalDev\RocktimeLogic\NET\10-FixingRefs\TestUpgrade\TestUpgrade.vbproj'...

Analyzing selected projects and their dependencies...

TestUpgrade 100%

System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.ArgumentNullException.Throw(String paramName)
   at System.String.StartsWith(String value)
   at Microsoft.UpgradeAssistant.Helpers.LocalPathHelper.PreprocessLocalPaths(String path, String rootPath, Boolean isProtected, IEnvironmentService
environment) in D:\a\_work\1\s\src\engine\Helpers\LocalPathHelper.cs:line 36
   at Microsoft.UpgradeAssistant.Analysis.ProjectAnalysis.GetEntryRelativePath(AnalysisEntry entry) in
D:\a\_work\1\s\src\engine\Analysis\ProjectAnalysis.cs:line 177
   at Microsoft.UpgradeAssistant.Analysis.AnalysisBase.GetReport() in D:\a\_work\1\s\src\engine\Analysis\AnalysisBase.cs:line 166
   at Microsoft.UpgradeAssistant.Cli.Flow.Steps.Analysis.RunAnalysisFlowStep.<>c__DisplayClass14_0.<GetReportAsync>b__0(StatusContext statusContext)
in D:\a\_work\1\s\src\cli\Flow\Steps\Analysis\RunAnalysisFlowStep.cs:line 155
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in /_/src/Spectre.Console/Live/Status/Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in /_/src/Spectre.Console/Live/Status/Status.cs:line 77
   at Microsoft.UpgradeAssistant.Cli.Flow.Steps.Analysis.RunAnalysisFlowStep.GetReportAsync(IAnalysis analysis, CancellationToken cancellationToken)
in D:\a\_work\1\s\src\cli\Flow\Steps\Analysis\RunAnalysisFlowStep.cs:line 151
   at Microsoft.UpgradeAssistant.Cli.Flow.Steps.Analysis.RunAnalysisFlowStep.RunAsync(IFlowContext context, CancellationToken cancellationToken) in
D:\a\_work\1\s\src\cli\Flow\Steps\Analysis\RunAnalysisFlowStep.cs:line 86
   at Spectre.Console.Flow.FlowRunner.RunAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\src\spectre.flow\Flow\FlowRunner.cs:line 98

The project file is

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{04383836-6FF9-44CE-91C8-63CFB2CFB8A8}</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>TestUpgrade</RootNamespace>
    <AssemblyName>TestUpgrade</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <MyType>Windows</MyType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>bin\Debug\</OutputPath>
    <DocumentationFile>TestUpgrade.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DocumentationFile>TestUpgrade.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>
  <PropertyGroup>
    <OptionCompare>Binary</OptionCompare>
  </PropertyGroup>
  <PropertyGroup>
    <OptionStrict>Off</OptionStrict>
  </PropertyGroup>
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Data" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Class1.vb" />
    <Compile Include="My Project\AssemblyInfo.vb" />
    <Compile Include="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Include="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="My Project\Resources.resx">
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Include="My Project\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <CustomToolNamespace>My</CustomToolNamespace>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" />
</Project>

**Comment by douglasware** [comment]
Seems the same bug as this: https://github.com/dotnet/upgrade-assistant/issues/1575 which is marked "Fixed" but isn't
